package com.luxsoft.replica

import java.util.List;

class EntityModelFactory {
	
	def static models=[:]
	
	
	
	static getModel(String name){
		switch (name) {
			case "Existencia":
				return new EntityModel(name:name,table:"SX_EXISTENCIAS"
				,columnId:"INVENTARIO_ID"
				,insertSql:"""INSERT INTO SX_EXISTENCIAS
					(INVENTARIO_ID,CANTIDAD,CLAVE,COSTO,COSTOP,COSTOU,CREADO,CREADO_USERID,DESCRIPCION,FACTORU,FECHA,TX_IMPORTADO,KILOS,MES,MODIFICADO,NACIONAL,RECORTE,RECORTE_COMENTARIO,RECORTE_FECHA,TX_REPLICADO,UNIDAD,MODIFICADO_USERID,version,YEAR,SUCURSAL_ID
					,PRODUCTO_ID)
			
				"""
				,updateSql:"""
					UPDATE SX_EXISTENCIAS SET
					SUCURSAL_ID=:SUCURSAL_ID,PRODUCTO_ID=:PRODUCTO_ID
					,CLAVE=:CLAVE,MES=:MES,YEAR=:YEAR,CANTIDAD=:CANTIDAD
					,UNIDAD=:UNIDAD
					,FACTORU=:FACTORU,FECHA=:FECHA
					,COSTO=:COSTO
					,COSTOP=:COSTOP,COSTOU=:COSTOP,DESCRIPCION=:DESCRIPCION
					,CREADO=:CREADO,CREADO_USERID=:CREADO_USERID,MODIFICADO=:MODIFICADO
					,MODIFICADO_USERID=:MODIFICADO_USERID
					,version=:version,KILOS=:KILOS,NACIONAL=:NACIONAL,RECORTE=:RECORTE
					,TX_IMPORTADO=:TX_IMPORTADO,TX_REPLICADO=:TX_REPLICADO,RECORTE_COMENTARIO=:RECORTE_COMENTARIO,RECORTE_FECHA=:RECORTE_FECHA 
					WHERE INVENTARIO_ID=:INVENTARIO_ID
				"""
				)
				//break;
			case "Movimiento":
				return new EntityModel(name:name,table:"SX_MOVI"
					,columnId:"MOVI_ID"
					,insertSql:"""
					"""
					,updateSql:"""
					UPDATE SX_MOVI SET COMENTARIO=:COMENTARIO,CONCEPTO=:CONCEPTO,FECHA=:FECHA,CREADO=:CREADO,MODIFICADO=:MODIFICADO,version=:version,DOCUMENTO=:DOCUMENTO,TX_IMPORTADO=:TX_IMPORTADO,TX_REPLICADO=:TX_REPLICADO,PORINVENTARIO=:PORINVENTARIO
					WHERE MOVI_ID:MOVI_ID
					"""
				)
			case "MovimientoDet":
				return new EntityModel(name:name,table:"SX_INVENTARIO_MOV"
					,columnId:"INVENTARIO_ID"
					,insertSql:"""
					
					"""
					,updateSql:"""
					UPDATE SX_INVENTARIO_MOV SET CANTIDAD=:CANTIDAD,CLAVE=:CLAVE,COMENTARIO=:COMENTARIO,COSTO=:COSTO,COSTOP=:COSTOP,COSTOU=:COSTOU,CREADO=:CREADO,DESCRIPCION=:DESCRIPCION,DOCUMENTO=:DOCUMENTO,FACTORU=:FACTORU,FECHA=:FECHA,MODIFICADO=:MODIFICADO,NACIONAL=:NACIONAL,RENGLON=:RENGLON,version=:version,COMENTARIO2=:COMENTARIO2,CONCEPTO=:CONCEPTO,KILOS=:KILOS,EXISTENCIA=:EXISTENCIA,TIPO_CIS=:TIPO_CIS 
					WHERE MOVI_ID=:MOVI_ID
					"""
				)
			case "Venta":
				return new EntityModel(name:name,table:"SX_VENTAS"
				,columnId:"CARGO_ID"
				,insertSql:"""
					"""
				,updateSql:"""
					UPDATE SX_VENTAS SET TIPO=:TIPO,CARGO_ID=:CARGO_ID,CARGOS=:CARGOS,CLAVE=:CLAVE,COMENTARIO=:COMENTARIO
					,COMENTARIO2=:COMENTARIO2,COMENTARIO_REP_PAGO=:COMENTARIO_REP_PAGO,DESCRI_CARGO=:DESCRI_CARGO
					,DESCUENTO=:DESCUENTO,DIA_DEL_PAGO=:DIA_DEL_PAGO,DIA_PAGO=:DIA_PAGO,DIA_DE_REV=:DIA_DE_REV,DOCTO=:DOCTO
						,FECHA=:FECHA,FECHA_RECEPCION_CXC=:FECHA_RECEPCION_CXC,FECHA_REVISION=:FECHA_REVISION,FECHA_REVISION_CXC=:FECHA_REVISION_CXC
						,IMPORTE=:IMPORTE,IMPRESO=:IMPRESO,IMPUESTO=:IMPUESTO,CREADO=:CREADO,CREADO_USERID=:CREADO_USERID,MODIFICADO=:MODIFICADO
					,MODIFICADO_USERID=:MODIFICADO_USERID,MONEDA=:MONEDA,NOMBRE=:NOMBRE,NFISCAL=:NFISCAL,ORIGEN=:ORIGEN,PLAZO=:PLAZO
					,POST_FECHADO=:POST_FECHADO,PRECIO_BRUTO=:PRECIO_BRUTO,REPROGRAMAR_PAGO=:REPROGRAMAR_PAGO,REVISADA=:REVISADA,REVISION=:REVISION
					,SALDO=:SALDO,SIIPAPWIN_ID=:SIIPAPWIN_ID,TC=:TC,TOTAL=:TOTAL,VTO=:VTO,version=:version,CANCELACION_DBF=:CANCELACION_DBF
					,CANCELACION_DBF_COM=:CANCELACION_DBF_COM,ORIGEN_IMPORTACION=:ORIGEN_IMPORTACION,SERIE_SIP=:SERIE_SIP,SURTIDOR=:SURTIDOR,TIPO_SIP=:TIPO_SIP
					,CARGO=:CARGO,VENDEDOR_ID=:VENDEDOR_ID,SUCURSAL_ID=:SUCURSAL_ID,CLIENTE_ID=:CLIENTE_ID,SOCIO_ID=:SOCIO_ID,COBRADOR_ID=:COBRADOR_ID
					,CHEQUE_ID=:CHEQUE_ID,DIF_CONCEPTO=:DIF_CONCEPTO,FLETE=:FLETE,FPAGO=:FPAGO,AUT_SIN_EXIS_ID=:AUT_SIN_EXIS_ID,CE=:CE
					,TX_IMPORTADO=:TX_IMPORTADO,TX_REPLICADO=:TX_REPLICADO,COMPRADOR=:COMPRADOR,INSTRUCCION_ENTREGA=:INSTRUCCION_ENTREGA,KILOS=:KILOS,PEDIDO_CREADO_USERID=:PEDIDO_CREADO_USERID,PEDIDO_IP_CREATED=:PEDIDO_IP_CREATED,PEDIDO_FOLIO=:PEDIDO_FOLIO
					,PEDIDO_FENTREGA=:PEDIDO_FENTREGA
					,PUESTO=:PUESTO,MISMA=:MISMA,ANTICIPO=:ANTICIPO,ANTICIPO_APLICADO=:ANTICIPO_APLICADO 
						WHERE CARGO_ID=:CARGO_ID
					"""
				,excludeColumns:['PEDIDO_ID']
				)
			case "VentaDet":
				return new EntityModel(name:name,table:"SX_VENTASDET"
				,columnId:"INVENTARIO_ID"
				,insertSql:"""
					
					"""
				,updateSql:"""
					UPDATE SX_VENTASDET SET CANTIDAD=:CANTIDAD,CLAVE=:CLAVE,COMENTARIO=:COMENTARIO,COSTO=:COSTO,COSTOP=:COSTOP,COSTOU=:COSTOU
				,CREADO=:CREADO,DESCRIPCION=:DESCRIPCION,DOCUMENTO=:DOCUMENTO,FACTORU=:FACTORU,FECHA=:FECHA,MODIFICADO=:MODIFICADO
				,NACIONAL=:NACIONAL,RENGLON=:RENGLON,version=:version,CORTES=:CORTES,DSCTO=:DSCTO,DSCTO_NOTA=:DSCTO_NOTA
				,DSCTO_ORIG=:DSCTO_ORIG,IMPORTE=:IMPORTE,IMPORTE_NETO=:IMPORTE_NETO,PRECIO=:PRECIO,PRECIO_CORTES=:PRECIO_CORTES,PRECIO_L=:PRECIO_L,SERIE=:SERIE,SUBTOTAL=:SUBTOTAL,TIPO=:TIPO,IDX=:IDX,KILOS=:KILOS,EXISTENCIA=:EXISTENCIA,CORTE_ANCHO=:CORTE_ANCHO
				,CORTE_LARGO=:CORTE_LARGO,CORTES_INSTRUCCION=:CORTES_INSTRUCCION,ORDENP=:ORDENP,VENTA_ID=:VENTA_ID
				WHERE INVENTARIO_ID=:INVENTARIO_ID
					"""
				)
			case "PagoConEfectivo":
				return new EntityModel(name:name,table:"SX_CXC_ABONOS"
					,columnId:"ABONO_ID"
					,insertSql:"""
					"""
					,updateSql:"""
					UPDATE SX_CXC_ABONOS SET TIPO_ID=:TIPO_ID,CLAVE=:CLAVE,COMENTARIO=:COMENTARIO,FECHA=:FECHA,IMPORTE=:IMPORTE,IMPUESTO=:IMPUESTO,CREADO=:CREADO,CREADO_USERID=:CREADO_USERID,MODIFICADO=:MODIFICADO,MODIFICADO_USERID=:MODIFICADO_USERID,MONEDA=:MONEDA,NOMBRE=:NOMBRE,ORIGEN=:ORIGEN,SIIPAP_ID=:SIIPAP_ID,TC=:TC,TOTAL=:TOTAL,version=:version,APLICABLE=:APLICABLE,COMENTARIO2=:COMENTARIO2,DESCUENTO=:DESCUENTO,FOLIO=:FOLIO,IMPRESO=:IMPRESO,TIPO=:TIPO,CONCEPTO=:CONCEPTO,MODO_CALCULO=:MODO_CALCULO,TIPO_DEV=:TIPO_DEV,ANTICIPO=:ANTICIPO,BANCO=:BANCO,CUENTA_CLIENTE=:CUENTA_CLIENTE,CUENTA_HABIENTE=:CUENTA_HABIENTE,ENVIADO=:ENVIADO,numero=:numero,postFechado=:postFechado,VTO=:VTO,CHEQUE=:CHEQUE,EFECTIVO=:EFECTIVO,REFERENCIA=:REFERENCIA,TRANSFERENCIA=:TRANSFERENCIA,AUTO_TARJETA_BANCO=:AUTO_TARJETA_BANCO,COMISION_TARJETA=:COMISION_TARJETA,DIF_CAMBIARIA=:DIF_CAMBIARIA,CLIENTE_ID=:CLIENTE_ID,COBRADOR_ID=:COBRADOR_ID,ESQUEMA_ID=:ESQUEMA_ID,SUCURSAL_ID=:SUCURSAL_ID,TARJETA_ID=:TARJETA_ID,CUENTA_ID=:CUENTA_ID,DEVOLUCION_ID=:DEVOLUCION_ID,REC_DEVUELTO=:REC_DEVUELTO,AUTORIZACION_ID=:AUTORIZACION_ID,LIBERADO=:LIBERADO,FECHA_DEPOSITO=:FECHA_DEPOSITO,SALVO_COBRO=:SALVO_COBRO,SAF=:SAF,DIFERENCIA=:DIFERENCIA,DIFERENCIA_FECHA=:DIFERENCIA_FECHA,TX_IMPORTADO=:TX_IMPORTADO,TX_REPLICADO=:TX_REPLICADO 
					WHERE ABONO_ID=:ABONO_ID
					"""
					,excludeColumns:['DISPONIBLE']
				)
			case "AplicacionDePago":
				return new EntityModel(name:name,table:"SX_CXC_APLICACIONES"
					,columnId:"APLICACION_ID"
					,insertSql:"""
					"""
					,updateSql:"""
					UPDATE SX_CXC_APLICACIONES SET TIPO=:TIPO,COMENTARIO=:COMENTARIO,DESCUENT_NOTA=:DESCUENT_NOTA,ABN_BANCO=:ABN_BANCO,CLAVE=:CLAVE,CAR_DOCTO=:CAR_DOCTO,ABN_FOLIO=:ABN_FOLIO,ABN_DESCRIPCION=:ABN_DESCRIPCION,NOMBRE=:NOMBRE,CAR_ORIGEN=:CAR_ORIGEN,CAR_POSTF=:CAR_POSTF,CAR_PBRUTO=:CAR_PBRUTO,CAR_SUCURSAL=:CAR_SUCURSAL,fecha=:fecha,IMPORTE=:IMPORTE,CREADO=:CREADO,CREADO_USERID=:CREADO_USERID,MODIFICADO=:MODIFICADO,MODIFICADO_USERID=:MODIFICADO_USERID,SIIPAP_ID=:SIIPAP_ID,ABONO_ID=:ABONO_ID,CARGO_ID=:CARGO_ID,RENGLON=:RENGLON,CAR_JURIDICO=:CAR_JURIDICO,AUTORIZACION_ID=:AUTORIZACION_ID,CE=:CE,CAR_FECHA=:CAR_FECHA,CAR_TOTAL=:CAR_TOTAL,CAR_TIPO=:CAR_TIPO,CAR_ANTICIPO=:CAR_ANTICIPO
					 WHERE APLICACION_ID=:APLICACION_ID
					"""
					
				)
			case "ComprobanteFiscal":
				return new EntityModel(name:name,table:"SX_CFD"
					,columnId:"CFD_ID"
					,insertSql:"""
					"""
					,updateSql:"""
						UPDATE SX_CFD SET TIPO=:TIPO,SERIE=:SERIE,FOLIO=:FOLIO,ANO_APROBACION=:ANO_APROBACION,XML_PATH=:XML_PATH,XML_SCHEMA_VERSION=:XML_SCHEMA_VERSION,NO_APROBACION=:NO_APROBACION,NO_CERTIFICADO=:NO_CERTIFICADO,ORIGEN_ID=:ORIGEN_ID,RECEPTOR=:RECEPTOR,EMISOR=:EMISOR,CREADO=:CREADO,CREADO_USR=:CREADO_USR,MODIFICADO=:MODIFICADO,MODIFICADO_USR=:MODIFICADO_USR,TX_REPLICADO=:TX_REPLICADO,TX_IMPORTADO=:TX_IMPORTADO,version=:version,TIPO_CFD=:TIPO_CFD,ADUANA=:ADUANA,CUENTA_PREDIAL=:CUENTA_PREDIAL,ESTADO=:ESTADO,IMPUESTO=:IMPUESTO,PEDIMENTO=:PEDIMENTO,PEDIMENTO_FECHA=:PEDIMENTO_FECHA,RFC=:RFC,TOTAL=:TOTAL 
						WHERE CFD_ID=:CFD_ID
					"""
				)
			case "Compra2":
				return new EntityModel(name:name,table:"SX_COMPRAS2"
					,columnId:"COMPRA_ID"
					,insertSql:"""
					"""
					,updateSql:"""
						UPDATE SX_COMPRAS2 SET TIPO=:TIPO,CIERRE=:CIERRE,CLAVE=:CLAVE,COMENTARIO=:COMENTARIO,COMENTARIO_REC=:COMENTARIO_REC,DEPURACION=:DEPURACION,DOCTO=:DOCTO,ENTREGA=:ENTREGA,FECHA=:FECHA,FOLIO=:FOLIO,IMPORTE_BRUTO=:IMPORTE_BRUTO,IMPORTE_DESC=:IMPORTE_DESC,IMPORTE_NETO=:IMPORTE_NETO,IMPUESTOS=:IMPUESTOS,CREADO=:CREADO,CREADO_USR=:CREADO_USR,MODIFICADO=:MODIFICADO,MODIFICADO_USR=:MODIFICADO_USR,MONEDA=:MONEDA,NOMBRE=:NOMBRE,PENDIENTE=:PENDIENTE,SUBTOTAL=:SUBTOTAL,TC=:TC,TOTAL=:TOTAL,version=:version,SUCURSAL_ID=:SUCURSAL_ID,PROVEEDOR_ID=:PROVEEDOR_ID,TX_IMPORTADO=:TX_IMPORTADO,TX_REPLICADO=:TX_REPLICADO,CONSOLIDADA=:CONSOLIDADA,IMPORTACION=:IMPORTACION,ESPECIAL=:ESPECIAL,DSCTO_ESPECIAL=:DSCTO_ESPECIAL
						WHERE COMPRA_ID=:COMPRA_ID
					"""
				)
			case "CompraUnitaria":
				return new EntityModel(name:name,table:"SX_COMPRAS2_DET"
					,columnId:"COMPRADET_ID"
					,insertSql:"""
					"""
					,updateSql:"""
						UPDATE SX_COMPRAS2_DET SET CLAVE=:CLAVE,COMENTARIO=:COMENTARIO,COSTO=:COSTO,DEPURACION=:DEPURACION,DEPURADO=:DEPURADO
					,DESC1=:DESC1,DESC2=:DESC2,DESC3=:DESC3,DESC4=:DESC4,DESC5=:DESC5,DESC6=:DESC6,DESCRIPCION=:DESCRIPCION,DESCF=:DESCF
					,FACTOR=:FACTOR,IMPORTE_BRUTO=:IMPORTE_BRUTO,IMPORTE_DESC=:IMPORTE_DESC,IMPORTE_NETO=:IMPORTE_NETO
					,PRECIO=:PRECIO,SOLICITADO=:SOLICITADO,SUC_NAME=:SUC_NAME,UNIDAD=:UNIDAD,version=:version,SUCURSAL_ID=:SUCURSAL_ID
					,PRODUCTO_ID=:PRODUCTO_ID,COMPRA_ID=:COMPRA_ID,FOLIO_ORIGEN=:FOLIO_ORIGEN,ADUANA=:ADUANA,REGISTRO_ADUANA=:REGISTRO_ADUANA,RECIBIDO_GLOBAL=:RECIBIDO_GLOBAL
					 WHERE COMPRADET_ID=:COMPRADET_ID
					"""
					
				)
			case "RecepcionDeCompra":
				return new EntityModel(name:name,table:"SX_ENTRADA_COMPRAS"
					,columnId:"ID"
					,insertSql:"""
					"""
					,updateSql:"""
						UPDATE SX_ENTRADA_COMPRAS SET COMENTARIO=:COMENTARIO,FECHA=:FECHA,CREADO=:CREADO,CREADO_USR=:CREADO_USR
						,MODIFICADO=:MODIFICADO,MODIFICADO_USR=:MODIFICADO_USR,REMISION=:REMISION,version=:version
						,COMPRA_ID=:COMPRA_ID,SUCURSAL_ID=:SUCURSAL_ID
						,DOCUMENTO=:DOCUMENTO,TX_IMPORTADO=:TX_IMPORTADO,TX_REPLICADO=:TX_REPLICADO
						 WHERE ID=:ID
					"""
				)
			case "EntradaPorCompra":
				return new EntityModel(name:name,table:"SX_INVENTARIO_COM"
					,columnId:"INVENTARIO_ID"
					,insertSql:"""
					"""
					,updateSql:"""
						UPDATE SX_INVENTARIO_COM SET ALMACEN_ID=:ALMACEN_ID,CANTIDAD=:CANTIDAD,CLAVE=:CLAVE,COMENTARIO=:COMENTARIO,COSTO=:COSTO,COSTOP=:COSTOP,COSTOU=:COSTOU,CREADO=:CREADO,CREADO_USERID=:CREADO_USERID,DESCRIPCION=:DESCRIPCION,DOCUMENTO=:DOCUMENTO,FACTORU=:FACTORU,FECHA=:FECHA,MODIFICADO=:MODIFICADO,NACIONAL=:NACIONAL,RENGLON=:RENGLON,MODIFICADO_USERID=:MODIFICADO_USERID,version=:version,UNIDAD_ID=:UNIDAD_ID,SUCURSAL_ID=:SUCURSAL_ID,PRODUCTO_ID=:PRODUCTO_ID,COMPRA=:COMPRA,COMS2_ID=:COMS2_ID,COMPRA_F=:COMPRA_F,REMISION_F=:REMISION_F,REMISION=:REMISION,SUCCOM=:SUCCOM,PROVEEDOR_ID=:PROVEEDOR_ID,COMPRA_ID=:COMPRA_ID,KILOS=:KILOS,EXISTENCIA=:EXISTENCIA,RECEPCION_ID=:RECEPCION_ID,COMPRADET_ID=:COMPRADET_ID,COSTO_FLETE=:COSTO_FLETE,ANALISIS_FLETE_ID=:ANALISIS_FLETE_ID,COSTO_MP=:COSTO_MP,COSTO_GASTO=:COSTO_GASTO,ANALISIS_GASTO_ID=:ANALISIS_GASTO_ID
					 	WHERE INVENTARIO_ID=:INVENTARIO_ID
					"""
				)
			case "DevolucionDeCompra":
				return new EntityModel(name:name,table:"SX_DEVOLUCION_COMPRAS"
					,columnId:"DEVOLUCION_ID"
					,insertSql:"""
					"""
					,updateSql:"""
						UPDATE SX_DEVOLUCION_COMPRAS SET PROVEEDOR_ID=:PROVEEDOR_ID,SUCURSAL_ID=:SUCURSAL_ID,REFERENCIA=:REFERENCIA,DOCUMENTO=:DOCUMENTO,FECHA=:FECHA,CLAVE=:CLAVE,NOMBRE=:NOMBRE,COMENTARIO=:COMENTARIO,TX_IMPORTADO=:TX_IMPORTADO,TX_REPLICADO=:TX_REPLICADO,CREADO=:CREADO,CREADO_USR=:CREADO_USR,MODIFICADO=:MODIFICADO,MODIFICADO_USR=:MODIFICADO_USR,CREATED_IP=:CREATED_IP,CREATED_MAC=:CREATED_MAC,UPDATED_IP=:UPDATED_IP,UPDATED_MAC=:UPDATED_MAC,version=:version
					 WHERE DEVOLUCION_ID=:DEVOLUCION_ID
					"""
				)
			case "DevolucionDeCompraDet":
				return new EntityModel(name:name,table:"SX_INVENTARIO_DEC"
					,columnId:"INVENTARIO_ID"
					,insertSql:"""
					"""
					,updateSql:"""
					UPDATE SX_INVENTARIO_DEC SET ALMACEN_ID=:ALMACEN_ID,CANTIDAD=:CANTIDAD,CLAVE=:CLAVE,COMENTARIO=:COMENTARIO,COSTO=:COSTO,COSTOP=:COSTOP,COSTOU=:COSTOU,CREADO=:CREADO,CREADO_USERID=:CREADO_USERID,DESCRIPCION=:DESCRIPCION,DOCUMENTO=:DOCUMENTO,EXISTENCIA=:EXISTENCIA,FACTORU=:FACTORU,FECHA=:FECHA,KILOS=:KILOS,MODIFICADO=:MODIFICADO,NACIONAL=:NACIONAL,RENGLON=:RENGLON,MODIFICADO_USERID=:MODIFICADO_USERID,version=:version,SUCURSAL_ID=:SUCURSAL_ID,PRODUCTO_ID=:PRODUCTO_ID,UNIDAD_ID=:UNIDAD_ID,DEVOLUCION_ID=:DEVOLUCION_ID
					 WHERE INVENTARIO_ID=:INVENTARIO_ID
					"""
				)
			case "RecepcionDeMaquila":
				return new EntityModel(name:name,table:"SX_RECEPCION_MAQUILA"
					,columnId:"ID"
					,insertSql:"""
					"""
					,updateSql:"""
						UPDATE SX_RECEPCION_MAQUILA SET comentario=:comentario,DOCUMENTO=:DOCUMENTO,FECHA=:FECHA,CREADO=:CREADO,CREADO_USR=:CREADO_USR,MODIFICADO=:MODIFICADO,MODIFICADO_USR=:MODIFICADO_USR,REMISION=:REMISION,version=:version,SUCURSAL_ID=:SUCURSAL_ID,PROVEEDOR_ID=:PROVEEDOR_ID,createdIp=:createdIp,createdMac=:createdMac,updatedIp=:updatedIp,updatedMac=:updatedMac,TX_IMPORTADO=:TX_IMPORTADO,TX_REPLICADO=:TX_REPLICADO
					 WHERE ID=:ID
					"""
				)
			case "EntradaDeMaquila":
				return new EntityModel(name:name,table:"SX_INVENTARIO_MAQ"
					,columnId:"INVENTARIO_ID"
					,insertSql:"""
					"""
					,updateSql:"""
						UPDATE SX_INVENTARIO_MAQ SET ALMACEN_ID=:ALMACEN_ID,CANTIDAD=:CANTIDAD,CLAVE=:CLAVE,COMENTARIO=:COMENTARIO,COSTO=:COSTO,COSTOP=:COSTOP,COSTOU=:COSTOU,CREADO=:CREADO,CREADO_USERID=:CREADO_USERID,DESCRIPCION=:DESCRIPCION,DOCUMENTO=:DOCUMENTO,FACTORU=:FACTORU,FECHA=:FECHA,MODIFICADO=:MODIFICADO,NACIONAL=:NACIONAL,RENGLON=:RENGLON,MODIFICADO_USERID=:MODIFICADO_USERID,version=:version,UNIDAD_ID=:UNIDAD_ID,SUCURSAL_ID=:SUCURSAL_ID,PRODUCTO_ID=:PRODUCTO_ID,REMISION_F=:REMISION_F,MAQUILA_ID=:MAQUILA_ID,MAQUILADOR=:MAQUILADOR,REMISION=:REMISION,MAQUILA_TIPO=:MAQUILA_TIPO,KILOS=:KILOS,EXISTENCIA=:EXISTENCIA,COSTO_CORTE=:COSTO_CORTE,COSTO_FLETE=:COSTO_FLETE,COSTO_MP=:COSTO_MP,RECEPCION_ID=:RECEPCION_ID,ANALISIS_ID=:ANALISIS_ID,ANALISIS_FLETE_ID=:ANALISIS_FLETE_ID,ANALISIS_HOJEO_ID=:ANALISIS_HOJEO_ID
					 WHERE INVENTARIO_ID=:INVENTARIO_ID,
					"""
				)
			case "Transformacion":
				return new EntityModel(name:name,table:"SX_TRANSFORMACIONES"
					,columnId:"TRANSFORMACION_ID"
					,insertSql:"""
					"""
					,updateSql:"""
						UPDATE SX_TRANSFORMACIONES SET CLASE=:CLASE,COMENTARIO=:COMENTARIO,DOCUMENTO=:DOCUMENTO,FECHA=:FECHA,GASTO=:GASTO
						,PORINVENTARIO=:PORINVENTARIO,CREADO=:CREADO,CREADO_USERID=:CREADO_USERID,MODIFICADO=:MODIFICADO
						,MODIFICADO_USERID=:MODIFICADO_USERID,version=:version,SUCURSAL_ID=:SUCURSAL_ID
						WHERE TRANSFORMACION_ID=:TRANSFORMACION_ID
					"""
				)
			case "TransformacionDet":
				return new EntityModel(name:name,table:"SX_INVENTARIO_TRS"
					,columnId:"INVENTARIO_ID"
					,insertSql:"""
					"""
					,updateSql:"""
						UPDATE SX_INVENTARIO_TRS SET ALMACEN_ID=:ALMACEN_ID,CANTIDAD=:CANTIDAD,CLAVE=:CLAVE
						,COMENTARIO=:COMENTARIO,COSTO=:COSTO,COSTOP=:COSTOP,COSTOU=:COSTOU,CREADO=:CREADO,CREADO_USERID=:CREADO_USERID
						,DESCRIPCION=:DESCRIPCION,DOCUMENTO=:DOCUMENTO,FACTORU=:FACTORU,FECHA=:FECHA,MODIFICADO=:MODIFICADO,NACIONAL=:NACIONAL,RENGLON=:RENGLON,MODIFICADO_USERID=:MODIFICADO_USERID,version=:version
						,PRODUCTO_ID=:PRODUCTO_ID,SUCURSAL_ID=:SUCURSAL_ID,UNIDAD_ID=:UNIDAD_ID,GASTO_COMENTARIO=:GASTO_COMENTARIO,TRTIP=:TRTIP,costoOrigen=:costoOrigen
						,GASTO_DOCTO=:GASTO_DOCTO,gastos=:gastos,DESTINO_ID=:DESTINO_ID,KILOS=:KILOS,EXISTENCIA=:EXISTENCIA,TRANSFORMACION_ID=:TRANSFORMACION_ID
						,ANALISIS_ID=:ANALISIS_ID,COSTO_FLETE=:COSTO_FLETE,COSTO_CORTE=:COSTO_CORTE,ANALISIS_FLETE_ID=:ANALISIS_FLETE_ID,ANALISIS_HOJEO_ID=:ANALISIS_HOJEO_ID
						,REMISION=:REMISION 
						WHERE INVENTARIO_ID=:INVENTARIO_ID
					"""
				)
			
			default:
				return null;
				
			}
	}
	
	static entidades=[
		'ConceptoDeGasto':'SW_CONCEPTO_DE_GASTOS',
		'ServicioDeTransporte':'SX_TRANSPORTES_FORANEOS',
		'AutorizacionDeAplicacionCxC':'SX_AUTORIZACIONES2',
		'ExistenciaConteo':'SX_EXISTENCIA_CONTEO',
		'ListaDePreciosVentaDet':'SX_LP_VENT_DET',
		'ComisionVenta':'SX_COMISIONES',
		'CertificadoDeSelloDigital':'SX_CFD_CERTIFICADOS',
		'Autorizacion2':'SX_AUTORIZACIONES2',
		'AutorizacionDeAbono':'SX_AUTORIZACIONES2',
		'Concepto':'SW_CONCEPTOS',
		'Poliza':'SX_POLIZAS',
		'AplicacionDeAnticiposFacturados':'SX_ANTICIPOS_APLICADOS',
		'PagoDeDiferencias':'SX_CXC_ABONOS',
		'PreDevolucionDet':'SX_PREDEVOLUCIONES_DET',
		'SalidaPorVenta':'SX_INVENTARIO_FAC',
		'EntradaPorCompra':'SX_INVENTARIO_COM',
		'EntradaDeMaterialDet':'SX_MAQ_ENTRADASDET',
		'Juridico':'SX_JURIDICO',
		'CostoPromedio':'SX_COSTOS_P',
		'Transferencia':'SW_TRANSFERENCIAS',
		'Consignatario':'SW_CONSIGNATARIOS',
		'TransformacionDet':'SX_INVENTARIO_TRS',
		'Departamento':'SW_DEPARTAMENTOS',
		'CXPFactura':'SX_CXP',
		'InventarioAnual':'SX_INVENTARIO_INI',
		'AnalisisDeMaterial':'SX_MAQ_ANALISI_MAT',
		'GProveedor':'SW_GPROVEEDOR',
		'EntradaDeMaterial':'SX_MAQ_ENTRADAS',
		'ListaDePreciosDet':'SX_LP_PROVS_DET',
		'DevolucionDeCompra':'SX_DEVOLUCION_COMPRAS',
		'NotaDeCreditoDescuento':'SX_CXC_ABONOS',
		'DevolucionDeVenta':'SX_INVENTARIO_DEV',
		'ListaDePrecios':'SX_LP_PROVS',
		'Autorizacion':'SW_AUTORIZACIONES',
		'Inversion':'SX_TRASPASOS_CUENTAS',
		'DescuentoEspecial':'SX_VENTAS_DESCUENTOS',
		'Vendedor':'SX_VENDEDORES',
		'CXPAbono':'SX_CXP',
		'ListaDePreciosCliente':'SX_LP_CLIENTE',
		'Linea':'SX_LINEAS',
		'PolizaDet':'SX_POLIZASDET',
		'AplicacionDePago':'SX_CXC_APLICACIONES',
		'EmbarqueForaneo':'SX_EMBARQUES',
		'Kit':'SX_KITS',
		'User':'SX_USUARIOS',
		'SolicitudDeDeposito':'SX_SOLICITUDES_DEPOSITO',
		'NotaDeCargo':'SX_VENTAS',
		'Requisicion':'SW_TREQUISICION',
		'Tarjeta':'SX_TARJETAS',
		'CancelacionDeVenta':'SX_VENTAS_CANCELADAS',
		'PagoEnEspecie':'SX_CXC_ABONOS',
		'RequisicionDe':'SW_TREQUISICIONDET',
		'ComisionBancaria':'SX_COMISIONES_BANCARIAS',
		'EntregaDet':'SX_ENTREGAS_DET',
		'SolicitudDeEmbarque':'SX_EMBARQUE_SOLICITUDES',
		'TipoDeCliente':'SX_TIPO_CLIENTE',
		'CXPCargoAbono':'SX_CXP',
		'Cliente':'SX_CLIENTES',
		'SaldoDeCuenta':'SX_CONTABILIDAD_SALDOS',
		'PagoConDeposito':'SX_CXC_ABONOS',
		'Cargo':'SX_VENTAS',
		'Venta':'SX_VENTAS',
		'GFacturaPorCompra':'SW_FACTURAS_GASTOS',
		'CorteDeTarjeta':'SX_CORTE_TARJETAS',
		'CXPAnticipo':'SX_CXP',
		'NotaDeCreditoBonificacion':'SX_CXC_ABONOS',
		'AnalisisDeTransformacion':'SX_ANALISIS_TRS',
		'TrasladoDet':'SX_INVENTARIO_TRD',
		'Traslado':'SX_TRASLADOS',
		'CargoPorDiferencia':'SX_VENTAS',
		'Existencia':'SX_EXISTENCIAS',
		'Role':'SX_ROLE',
		'INPC':'SW_IPC',
		'Unidad':'SX_UNIDADES',
		'AutorizacionClientePCE':'SX_AUTORIZACIONES2',
		'CXPAplicacion':'SX_CXP_APLICACIONES',
		'ConteoDet':'SX_CONTEODET',
		'Empresa':'SW_EMPRESAS',
		'Clase':'SX_CLASES',
		'CompraUnitaria':'SX_COMPRAS2_DET',
		'RecepcionDeMaquila':'SX_RECEPCION_MAQUILA',
		'SaldoDeCuentaBancaria':'SW_CUENTAS_SALDOS',
		'AnalisisDeFacturaDet':'SX_ANALISISDET',
		'Conciliacion':'SW_CONCILIACION',
		'VentaDet':'SX_VENTASDET',
		'CancelacionDeAbono':'SX_CXC_ABONOS_CANCELADOS',
		'CorteDeTarjetaDet':'SX_CORTE_TARJETASDET',
		'Proveedor':'SX_PROVEEDORES',
		'CancelacionDeCargo':'SX_CXC_CARGOS_CANCELADOS',
		'Permiso':'SX_PERMISOS',
		'ListaDePreciosVenta':'SX_LP_VENT',
		'ListaDePreciosClienteDet':'SX_LP_CLIENTE_DET',
		'Zona':'SX_EMBARQUE_ZONAS',
		'Marca':'SX_MARCAS',
		'AplicacionDeNota':'SX_CXC_APLICACIONES',
		'Compra2':'SX_COMPRAS2',
		'ConfiguracionKit':'SX_KITCONFIG',
		'Abono':'SX_CXC_ABONOS',
		'FolioFiscal':'SX_CFD_FOLIOS',
		'SaldoDeCuentaPorConcepto':'SX_CONTABILIDAD_SALDOSDET',
		'DevolucionDeCompraDet':'SX_INVENTARIO_DEC',
		'AnalisisDeFactura':'SX_ANALISIS',
		'AutorizacionDeCargoCXP':'SX_AUTORIZACIONES2',
		'OrdenDeCorteDet':'SX_MAQ_ORDENESDET',
		'ConceptoContable':'SX_CONCEPTOS_CONTABLES',
		'PagoConTarjeta':'SX_CXC_ABONOS',
		'AutorizacionParaFacturarSinExistencia':'SX_AUTORIZACIONES2',
		'RecepcionDeCompra':'SX_ENTRADA_COMPRAS',
		'CXPAnalisisDet':'SX_CXP_ANALISISDET',
		'AutorizacionDeMovimiento':'SX_AUTORIZACIONES2',
		'SalidaDeHojasDet':'SX_MAQ_SALIDA_HOJEADODET',
		'NotaDeCredito':'SX_CXC_ABONOS',
		'SolicitudDeTraslado':'SX_SOLICITUD_TRASLADOS',
		'Producto':'SX_PRODUCTOS',
		'CXPNota':'SX_CXP',
		'AnticipoDeCompra':'SX_CXP_ANTICIPOS',
		'Aplicacion':'SX_CXC_APLICACIONES',
		'Ficha':'SX_FICHAS',
		'FichaDet':'SX_FICHASDET',
		'CorreccionDeFicha':'SX_FICHAS_CORRECIONES',
		'Chofer':'SX_CHOFERES',
		'GProductoServicio':'SW_GPRODUCTOSERVICIO',
		'AutorizacionParaCargo':'SX_AUTORIZACIONES2',
		'Banco':'SW_BANCOS',
		'AnalisisDeHojeo':'SX_MAQ_ANALISIS_HOJEO',
		'PagoDeRequisicion':'SW_TPAGO',
		'TraspasoDeCuenta':'SX_TRASPASOS_CUENTAS',
		'KitDet':'SX_INVENTARIO_KIT',
		'Sucursal':'SW_SUCURSALES',
		'Configuracion':'SX_CONFIGURACION',
		'OrdenDeCorte':'SX_MAQ_ORDENES',
		'Cobrador':'SX_COBRADORES',
		'CXPCargo':'SX_CXP',
		'Transformacion':'SX_TRANSFORMACIONES',
		'Entrega':'SX_ENTREGAS',
		'NotaDeCreditoDevolucion':'SX_CXC_ABONOS',
		'Pago':'SX_CXC_ABONOS',
		'CXPPago':'SX_CXP',
		'Almacen':'SX_ALMACENES',
		'ZonaDeEnvio':'SX_EMBARQUES_ZONAS_CARGO',
		'Devolucion':'SX_DEVOLUCIONES',
		'Esquema':'SX_ESQUEMAS',
		'MovimientoDet':'SX_INVENTARIO_MOV',
		'ChequeDevuelto':'SX_VENTAS',
		'ChoferFacturista':'SX_CHOFER_FACTURISTA',
		'ActivoFijo':'SW_ACTIVO_FIJO',
		'PreDevolucion':'SX_PREDEVOLUCIONES',
		'Asociado':'SX_SOCIOS',
		'AutorizacionDePedido':'SX_AUTORIZACIONES2',
		'GTipoProveedor':'SW_GTIPOS_DE_ROVEEDOR',
		'AnalisisDeFlete':'SX_MAQ_ANALISIS_FLETE',
		'PagoPorCambioDeCheque':'SX_CXC_ABONOS',
		'GCompraDet':'SW_GCOMPRADET',
		'NotaDeCargoDet':'SX_NOTADECARGO_DET',
		'ComprobanteFiscal':'SX_CFD',
		'Embarque':'SX_EMBARQUES',
		'EntradaDeMaquila':'SX_INVENTARIO_MAQ',
		'DescPorVol':'SX_DESC_VOL',
		'GCompra':'SW_GCOMPRA',
		'PagoConCheque':'SX_CXC_ABONOS',
		'NotaDeCreditoDet':'SX_NOTA_DET',
		'CuentaContable':'SX_CUENTAS_CONTABLES',
		'PagoConEfectivo':'SX_CXC_ABONOS',
		'RecepcionDeCorteDet':'SX_MAQ_RECEPCION_CORTEDET',
		'Movimiento':'SX_MOVI',
		'Cuenta':'SW_CUENTAS',
		'CargoAbono':'SW_BCARGOABONO',
		'ContraRecibo':'SX_CXP_RECIBOS',
		'MedidaPorCorte':'SX_CORTES_MEDIDAS',
		'Conteo':'SX_CONTEO',
		'Transporte':'SX_TRANSPORTES',
		'Socio':'SX_SOCIOS',
		'Corte':'SX_CORTES',
		'TipoDeCambio':'SX_TIPO_DE_CAMBIO',
		'SalidaDeBobinas':'SX_MAQ_SALIDA_BOBINAS',
		'ContraReciboDet':'SX_CXP_RECIBOS_DET',
		'ClienteCredito':'SX_CLIENTES_CREDITO',
		'DevolucionPorTesoreria':'SX_VENTAS',
		'CargoPorTesoreria':'SX_VENTAS',
		'ClasificacionDeActivo':'SW_ACTIVO_TIPO',
		'RecepcionDeCorte':'SX_MAQ_RECEPCION_CORTE',
		'ClientePorTonelada':'SX_EMBARQUES_CLIENTES_TON'
	]
	

}

class EntityModel{
	String name
	String table
	String columnId
	String insertSql
	String updateSql
	List excludeColumns
}
